<?php $featuredProductsCollection = $this->getFeaturedProductsCollection();?>
<?php $_helper = $this->helper('catalog/image');?>

<div class="megamenu-featured-products">
    <?php foreach($featuredProductsCollection as $featuredProduct):?>
        <div class="featured-product <?php echo $this->getDisplayClass();?>">
            <a href="<?php echo $featuredProduct->getProductUrl();?>">
                <?php if($featuredProduct->hasMenuImage()):?>
                    <?php $imageUrl = $_helper->init($featuredProduct, 'menu_image') ?>
                    <img src="<?php echo $imageUrl?>" />
                <?php endif;?>
                <?php echo $featuredProduct->getName(); ?>
            </a>
            <a class="button" href="<?php echo $featuredProduct->getProductUrl();?>"><span>View More</span></a>
        </div>
    <?php endforeach;?>
</div>