<?php
/**
 * @category    TheExtensionLab
 * @package     TheExtensionLab_MegaMenu
 * @copyright   Copyright (c) 2015 TheExtensionLab (http://www.theextensionlab.com)
 * @license     Open Software License (OSL 3.0)
 * @author      James Anelay @ TheExtensionLab <james@theextensionlab.com>
 */
?>

<?php $featuredProductsCollection = $this->getFeaturedProductsCollection();?>
<?php $_helper = $this->helper('catalog/image');?>

<div class="megamenu-featured-products secondary <?php echo $this->getDisplayClass();?>">

    <?php if($this->hasTitle()):?>
        <p class="section-title"><?php echo $this->getTitle();?></p>
    <?php endif;?>

    <?php foreach($featuredProductsCollection as $featuredProduct):?>
        <div class="featured-product">
            <a class="img" href="<?php echo $featuredProduct->getProductUrl();?>">
                <?php if($featuredProduct->hasMenuImage()):?>
                    <?php $imageUrl = $_helper->init($featuredProduct, 'menu_image') ?>
                    <img src="<?php echo $imageUrl?>" />
                <?php endif;?>
            </a>
            <div class="bd">
                <p><?php echo $featuredProduct->getName(); ?></p>
                <p><?php echo Mage::helper('core')->currency($featuredProduct->getFinalPrice(),true,true);?></p>
                <div class="button-container">
                    <a class="button" href="<?php echo $featuredProduct->getProductUrl();?>">
                        <span><?php echo $this->__('View More'); ?></span>
                    </a>
                </div>
            </div>
        </div>
    <?php endforeach;?>
</div>
