<?php
/**
 * @category    TheExtensionLab
 * @package     TheExtensionLab_MegaMenu
 * @copyright   Copyright (c) 2015 TheExtensionLab (http://www.theextensionlab.com)
 * @license     Open Software License (OSL 3.0)
 * @author      James Anelay @ TheExtensionLab <james@theextensionlab.com>
 */
?>

<?php $staticBlock = $this->getBlock();?>
<?php if($staticBlock):?>
    <?php echo $staticBlock->getContent();?>
<?php endif;?>