<?php
/**
 * @category    TheExtensionLab
 * @package     TheExtensionLab_MegaMenu
 * @copyright   Copyright (c) 2015 TheExtensionLab (http://www.theextensionlab.com)
 * @license     Open Software License (OSL 3.0)
 * @author      James Anelay @ TheExtensionLab <james@theextensionlab.com>
 */
?>

<?php /** @var $this TheExtensionLab_MegaMenu_Block_Widget_Category_Featured */
$featuredCategoryNode = $this->getFeaturedCategoryNode();?>

<?php if($featuredCategoryNode):?>
    <div class="featured-category featured-section <?php echo $this->getDisplayClass();?>">
        <a href="<?php echo $featuredCategoryNode->getUrl();?>">
            <?php if($this->hasFeaturedImage()):?>
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$this->getFeaturedImage();?>" />
            <?php endif;?>
            <?php if($this->hasTitle()):?>
                <span><?php echo $this->getTitle();?></span>
            <?php else:?>
                <span><?php echo $featuredCategoryNode->getName(); ?></span>
            <?php endif;?>
        </a>
    </div>
<?php endif;?>