<?php
/**
 * @category    TheExtensionLab
 * @package     TheExtensionLab_MegaMenu
 * @copyright   Copyright (c) 2015 TheExtensionLab (http://www.theextensionlab.com)
 * @license     http://www.theextensionlab.com/license/license.txt - Commercial License
 * @author      James Anelay @ TheExtensionLab <james@theextensionlab.com>
 */
?>

<?php $childNodes = $this->getLoadedMenuNodes(); ?>
<?php $categoryTree = $this->getCategoryTree(); ?>

<div class="list-block categories-list-block megamenu-list-block <?php echo $this->getDisplayClass();?>">
    <ul>
        <?php if($this->hasTitle()):?>
        <li class="section-title manual-section-title">
            <span>
                <?php echo $this->getTitle();?>
            </span>
        </li>
        <?php endif;?>

        <?php foreach($categoryTree as $category):?>
            <?php $categoryNode = $this->_getCategoryNodeById($childNodes, $category->id);?>
            <?php $categoryRenderer = $this->_getCategoryRenderer();?>

            <?php if($categoryNode):?>
                <li <?php if(!empty($category->children) && !$this->hasTitle()): echo 'class="section-title"';endif;?>>
                    <a href="<?php echo $categoryNode->getUrl(); ?>">
                        <span><?php echo $this->_getCustomCategoryMenuName($categoryNode,$category);?></span>
                    </a>
                </li>
            <?php endif; ?>

            <?php echo $categoryRenderer->render($category,$categoryNode,$childNodes);?>
        <?php endforeach; ?>
    </ul>
</div>