<?php /** @var $this  */
$featuredCmsPage = $this->getCmsPage()?>

<div class="featured-cms featured-section <?php echo $this->getDisplayClass();?>">
    <a href="<?php echo $this->getCmsPageUrl($featuredCmsPage);?>">
        <?php $imagePath = $featuredCmsPage->getMenuImage();?>
        <?php $imageUrl = Mage::helper('theextensionlab_megamenu/cms_page')->getFullImageUrl($imagePath); ?>
        <?php if($imageUrl):?>
            <img src="<?php echo $imageUrl?>" />
        <?php endif;?>
        <?php if($this->hasTitle()):?>
            <span><?php echo $this->getTitle();?></span>
        <?php else:?>
            <span><?php echo $featuredCmsPage->getTitle(); ?></span>
        <?php endif;?>
    </a>
</div>
