<?php
/**
 * @category    TheExtensionLab
 * @package     TheExtensionLab_MegaMenu
 * @copyright   Copyright (c) 2015 TheExtensionLab (http://www.theextensionlab.com)
 * @license     Open Software License (OSL 3.0)
 * @author      James Anelay @ TheExtensionLab <james@theextensionlab.com>
 */
?>

<?php $collection = Mage::registry('megamenu_attribute_options');?>
<?php $attributeCollection = Mage::registry('megamenu_attributes');?>

<?php $optionIds = $this->getOptionIds();?>

<?php $first_key = key($optionIds);?>

<?php if($attributeCollection && $attributeCollection):?>

    <?php $parentAttribute = $attributeCollection[$collection[$first_key]->getAttributeId()];?>

    <?php foreach($optionIds as $key => $value):?>
        <li>
            <a href="<?php echo Mage::helper('theextensionlab_megamenu/attribute_url')->getFilterUrl($this->getCategoryId(),$parentAttribute->getAttributeCode(),$key)?>">
                <span><?php echo $collection[$key]->getValue();?></span>
            </a>
        </li>
    <?php endforeach;?>

<?php endif;?>