<?php 
/**
 * Derivative work based on app/design/frontend/base/default/template/page/html/topmenu.phtml created by:
 * X.commerce, Inc. (http://www.magento.com)
 *
 * @copyright   Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * Changes by:  TheExtensionLab
 * @package     TheExtensionLab_MegaMenu
 * @copyright   Copyright (c) TheExtensionLab (http://www.theextensionlab.com)
 * @license     http://www.theextensionlab.com/license/license.txt - Commercial License
 * @author      James Anelay @ TheExtensionLab <james@theextensionlab.com>
 *
 */
?>

<?php /* Copy of RWD topmenu.phtml file apart from with out own ID and class so we
        can start the styles from scratch without specificity wars */ ?>
<?php $_menu = $this->getHtml('level-top') ?>
<?php $_responsiveFlag = Mage::getStoreConfigFlag('catalog/navigation/include_responsive_styles');?>

<?php if($_menu): ?>
    <nav id="megamenu-nav" class="megamenu-nav">
        <ol class="megamenu-nav-primary<?php if($_responsiveFlag):?> responsive<?php endif;?>" id="megamenu-nav-main" >
            <?php echo $_menu ?>
        </ol>
    </nav>
<?php endif ?>